export const SHOP_PATH = "/producten";

export const OI = {
  logo: "https://officeimage.nl/wp-content/uploads/2024/10/logo-nieuw.png",
  hero: "https://officeimage.nl/wp-content/uploads/2025/03/Luxe-kantoorinrichting.jpg",
  productCarousel: [
    {
      name: "Directie meubelen",
      img: "https://officeimage.nl/wp-content/uploads/2025/03/Luxe-kantoorinrichting.jpg",
      href: SHOP_PATH,
      tag: "Signatuur",
      line: "Representatieve directiekamers met hoogwaardige materialen en tijdloze uitstraling.",
      stat: "Exclusief bij OI",
    },
    {
      name: "Werkplekken",
      img: "https://officeimage.nl/wp-content/uploads/2020/07/HR_ZF3ZHFlaag_ret-scaled.jpg",
      href: SHOP_PATH,
      tag: "Foxline",
      line: "Modulaire, ergonomische werkplekken die meegroeien met uw organisatie.",
      stat: "Snel configureerbaar",
    },
    {
      name: "Archiefkasten",
      img: "https://officeimage.nl/wp-content/uploads/2024/10/roldeurkast-ch-1.jpg",
      href: SHOP_PATH,
      tag: "Opslag",
      line: "Roldeur, brandwerend en veilig. Groot op voorraad, direct leverbaar.",
      stat: "Grote voorraad",
    },
    {
      name: "Ladenkasten",
      img: "https://officeimage.nl/wp-content/uploads/2024/12/tekeningladekast-A3-8L-300x300-1.jpg",
      href: SHOP_PATH,
      tag: "Organisatie",
      line: "Ladenkasten en rolblokken voor een strak en overzichtelijk archief.",
      stat: "Diverse formaten",
    },
    {
      name: "Tafels",
      img: "https://officeimage.nl/wp-content/uploads/2025/03/HR_20230806_16-scaled.jpg",
      href: SHOP_PATH,
      tag: "Vergaderen",
      line: "Vergader en kantoortafels voor professionele ontmoetingsruimtes.",
      stat: "Op maat mogelijk",
    },
    {
      name: "Bureaustoelen en stoelen",
      img: "https://officeimage.nl/wp-content/uploads/2024/12/fede7c3c-3427-4597-80b1-9a169a5fd6a4.jpg",
      href: SHOP_PATH,
      tag: "Ergonomie",
      line: "24uurs stoelen en directiemodellen voor comfort tijdens lange werkdagen.",
      stat: "v.a. €669",
    },
    {
      name: "Lockers",
      img: "https://officeimage.nl/wp-content/uploads/2025/01/wrc.2.perfo_.bl-min_1.jpg",
      href: SHOP_PATH,
      tag: "Hybride werk",
      line: "Geperforeerde lockers en garderobes voor moderne flexkantoren.",
      stat: "RAL op aanvraag",
    },
    {
      name: "Kapstokken",
      img: "https://officeimage.nl/wp-content/uploads/2024/10/127.jpg",
      href: SHOP_PATH,
      tag: "Entree",
      line: "Stijlvolle kapstokken die de eerste indruk van uw kantoor versterken.",
      stat: "Snelle levering",
    },
  ],
  categories: [
    { name: "Directie meubelen", img: "https://officeimage.nl/wp-content/uploads/2025/03/Luxe-kantoorinrichting.jpg", href: SHOP_PATH },
    { name: "Werkplekken", img: "https://officeimage.nl/wp-content/uploads/2020/07/HR_ZF3ZHFlaag_ret-scaled.jpg", href: SHOP_PATH },
    { name: "Tafels", img: "https://officeimage.nl/wp-content/uploads/2025/03/HR_20230806_16-scaled.jpg", href: SHOP_PATH },
    { name: "Bureaustoelen en stoelen", img: "https://officeimage.nl/wp-content/uploads/2024/12/fede7c3c-3427-4597-80b1-9a169a5fd6a4.jpg", href: SHOP_PATH },
    { name: "Archiefkasten", img: "https://officeimage.nl/wp-content/uploads/2024/10/roldeurkast-ch-1.jpg", href: SHOP_PATH },
    { name: "Ladenkasten", img: "https://officeimage.nl/wp-content/uploads/2024/12/tekeningladekast-A3-8L-300x300-1.jpg", href: SHOP_PATH },
    { name: "Lockers", img: "https://officeimage.nl/wp-content/uploads/2025/01/wrc.2.perfo_.bl-min_1.jpg", href: SHOP_PATH },
    { name: "Kapstokken", img: "https://officeimage.nl/wp-content/uploads/2024/10/127.jpg", href: SHOP_PATH },
  ],
  bestsellers: [
    { name: "Bartafel Manage-it 220×80cm, Halifax", price: "€529", was: null, img: "https://officeimage.nl/wp-content/uploads/2026/04/HR_20161109_13_RobsonEiken-scaled.jpg", href: SHOP_PATH },
    { name: "Bartafel Manage-it 220×80cm", price: "€429", was: null, img: "https://officeimage.nl/wp-content/uploads/2026/04/HR_20161109_13_RobsonEiken-scaled.jpg", href: SHOP_PATH },
    { name: "Raptor 24uurs Bureaustoel, stof", price: "€669", was: "€749", img: "https://officeimage.nl/wp-content/uploads/2026/06/stoel_4A-scaled.jpg", href: SHOP_PATH },
    { name: "Raptor 24uurs Bureaustoel, leder", price: "€729", was: "€799", img: "https://officeimage.nl/wp-content/uploads/2026/06/stoel_3A-scaled.jpg", href: SHOP_PATH },
  ],
  showroom: {
    name: "Office Image Kantoormeubelen",
    address: "Industrieweg 167",
    zip: "3044 AS Rotterdam",
    tel: "010 230 99 44",
    telHref: "tel:0102309944",
    mobile: "+31 6 22778481",
    mobileHref: "tel:+31622778481",
    email: "info@officeimage.nl",
    kvk: "71542027",
  },
  social: {
    facebook: "https://www.facebook.com/officeimage.kantoormeubelen",
    instagram: "https://www.instagram.com/officeimage.kantoormeubelen/",
    linkedin: "https://www.linkedin.com/company/office-image-kantoormeubelen/",
  },
  hours: [
    ["Maandag", "09:00 tot 17:30"],
    ["Dinsdag", "09:00 tot 17:30"],
    ["Woensdag", "09:00 tot 17:30"],
    ["Donderdag", "09:00 tot 17:30"],
    ["Vrijdag", "09:00 tot 17:30"],
    ["Zaterdag", "11:00 tot 16:00"],
    ["Zondag", "Gesloten"],
  ] as const,
};

export type Bestseller = (typeof OI.bestsellers)[number];
