export const SHOP_PATH = "/producten";

export const OI = {
  logo: "https://officeimage.nl/wp-content/uploads/2024/10/logo-nieuw.png",
  hero: "https://officeimage.nl/wp-content/uploads/2025/03/Luxe-kantoorinrichting.jpg",
  media: {
    showroomStudio: "https://officeimage.nl/wp-content/uploads/2024/10/546-product_yHFOVOII.jpg",
    luxeKantoor: "https://officeimage.nl/wp-content/uploads/2025/03/Luxe-kantoorinrichting.jpg",
    armaDirectie: "https://officeimage.nl/wp-content/uploads/2024/10/ARMA-1.jpg",
    foxlineWerkplek: "https://officeimage.nl/wp-content/uploads/2024/10/fox-320x160-tafel-1-1.jpg",
    hrWerkplek: "https://officeimage.nl/wp-content/uploads/2020/07/HR_ZF3ZHFlaag_ret-scaled.jpg",
    hrVergader: "https://officeimage.nl/wp-content/uploads/2025/03/HR_20230806_16-scaled.jpg",
    raptorStoel: "https://officeimage.nl/wp-content/uploads/2026/06/stoel_4A-scaled.jpg",
    brandwerendArchief: "https://officeimage.nl/wp-content/uploads/2024/10/brandweerende-kast-1.jpg",
    heroSlides: {
      directie: "/images/hero/hero-directie-premium.webp",
      foxline: "/images/hero/hero-foxline-premium.webp",
      archief: "/images/hero/hero-archief-premium.webp",
    },
    lockersGarderobe: "https://officeimage.nl/wp-content/uploads/2024/10/okk-40_20120827164028.jpg",
    roldeurArchief: "https://officeimage.nl/wp-content/uploads/2024/10/roldeurkast3-1-600x600.png",
    archiefOpslag: "https://officeimage.nl/wp-content/uploads/2024/10/eco-rolblok-3.jpg",
    services: {
      inrichtingsadvies: "/images/services/inrichtingsadvies.webp",
      visualisatie3d: "/images/services/visualisatie-3d.webp",
      ergonomischAdvies: "/images/services/ergonomisch-advies.webp",
      leveringMontage: "/images/services/levering-montage.webp",
      onderhoudService: "/images/services/onderhoud-service.webp",
    },
    concepts: {
      directie: "/images/concepts/concept-directie.webp",
      werkplekken: "/images/concepts/concept-werkplekken.webp",
      bureaustoelen: "/images/concepts/concept-bureaustoelen.webp",
      archiefkasten: "/images/concepts/concept-archiefkasten.webp",
      lockers: "/images/concepts/concept-lockers.webp",
    },
    bestsellers: {
      bartafelHalifax: "/images/bestsellers/bestseller-bartafel-halifax.webp",
      bartafelVSerie: "/images/bestsellers/bestseller-bartafel-v-serie.webp",
      raptorStoel: "/images/bestsellers/bestseller-raptor-stoel.webp",
      stoel706cs: "/images/bestsellers/bestseller-706-cs.webp",
    },
    process: {
      adviesgesprek: "/images/process/process-adviesgesprek.webp",
      ruimteplan: "/images/process/process-ruimteplan.webp",
      visualisatie3d: "/images/process/process-3d-visualisatie.webp",
      productselectie: "/images/process/process-productselectie.webp",
      leveringMontage: "/images/process/process-levering-montage.webp",
      klanttevredenheid: "/images/process/process-klanttevredenheid.webp",
    },
  },
  productCarousel: [
    {
      name: "Directie meubelen",
      img: "https://officeimage.nl/wp-content/uploads/2025/03/Luxe-kantoorinrichting.jpg",
      href: SHOP_PATH,
      tag: "Signatuur",
      line: "Representatieve directiekamers met hoogwaardige materialen en tijdloze uitstraling.",
      stat: "Exclusief bij OI",
    },
    {
      name: "Werkplekken",
      img: "https://officeimage.nl/wp-content/uploads/2020/07/HR_ZF3ZHFlaag_ret-scaled.jpg",
      href: SHOP_PATH,
      tag: "Foxline",
      line: "Modulaire, ergonomische werkplekken die meegroeien met uw organisatie.",
      stat: "Snel configureerbaar",
    },
    {
      name: "Archiefkasten",
      img: "https://officeimage.nl/wp-content/uploads/2024/10/roldeurkast-ch-1.jpg",
      href: SHOP_PATH,
      tag: "Opslag",
      line: "Roldeur, brandwerend en veilig. Groot op voorraad, direct leverbaar.",
      stat: "Grote voorraad",
    },
    {
      name: "Ladenkasten",
      img: "https://officeimage.nl/wp-content/uploads/2024/12/tekeningladekast-A3-8L-300x300-1.jpg",
      href: SHOP_PATH,
      tag: "Organisatie",
      line: "Ladenkasten en rolblokken voor een strak en overzichtelijk archief.",
      stat: "Diverse formaten",
    },
    {
      name: "Tafels",
      img: "https://officeimage.nl/wp-content/uploads/2025/03/HR_20230806_16-scaled.jpg",
      href: SHOP_PATH,
      tag: "Vergaderen",
      line: "Vergader en kantoortafels voor professionele ontmoetingsruimtes.",
      stat: "Op maat mogelijk",
    },
    {
      name: "Bureaustoelen en stoelen",
      img: "https://officeimage.nl/wp-content/uploads/2024/12/fede7c3c-3427-4597-80b1-9a169a5fd6a4.jpg",
      href: SHOP_PATH,
      tag: "Ergonomie",
      line: "24uurs stoelen en directiemodellen voor comfort tijdens lange werkdagen.",
      stat: "v.a. €669",
    },
    {
      name: "Lockers",
      img: "https://officeimage.nl/wp-content/uploads/2025/01/wrc.2.perfo_.bl-min_1.jpg",
      href: SHOP_PATH,
      tag: "Hybride werk",
      line: "Geperforeerde lockers en garderobes voor moderne flexkantoren.",
      stat: "RAL op aanvraag",
    },
    {
      name: "Kapstokken",
      img: "https://officeimage.nl/wp-content/uploads/2024/10/127.jpg",
      href: SHOP_PATH,
      tag: "Entree",
      line: "Stijlvolle kapstokken die de eerste indruk van uw kantoor versterken.",
      stat: "Snelle levering",
    },
  ],
  categories: [
    { name: "Directie meubelen", img: "https://officeimage.nl/wp-content/uploads/2025/03/Luxe-kantoorinrichting.jpg", href: SHOP_PATH },
    { name: "Werkplekken", img: "https://officeimage.nl/wp-content/uploads/2020/07/HR_ZF3ZHFlaag_ret-scaled.jpg", href: SHOP_PATH },
    { name: "Tafels", img: "https://officeimage.nl/wp-content/uploads/2025/03/HR_20230806_16-scaled.jpg", href: SHOP_PATH },
    { name: "Bureaustoelen en stoelen", img: "https://officeimage.nl/wp-content/uploads/2024/12/fede7c3c-3427-4597-80b1-9a169a5fd6a4.jpg", href: SHOP_PATH },
    { name: "Archiefkasten", img: "https://officeimage.nl/wp-content/uploads/2024/10/roldeurkast-ch-1.jpg", href: SHOP_PATH },
    { name: "Ladenkasten", img: "https://officeimage.nl/wp-content/uploads/2024/12/tekeningladekast-A3-8L-300x300-1.jpg", href: SHOP_PATH },
    { name: "Lockers", img: "https://officeimage.nl/wp-content/uploads/2025/01/wrc.2.perfo_.bl-min_1.jpg", href: SHOP_PATH },
    { name: "Kapstokken", img: "https://officeimage.nl/wp-content/uploads/2024/10/127.jpg", href: SHOP_PATH },
  ],
  bestsellers: [
    {
      id: "bartafel-manage-it-halifax",
      name: "Bartafel Manage it 220×80cm, Halifax",
      price: "€529",
      was: null,
      img: "/images/bestsellers/bestseller-bartafel-halifax.webp",
      href: SHOP_PATH,
    },
    {
      id: "raptor-24uurs-stof",
      name: "Raptor 24uurs Bureaustoel, stof",
      price: "€669",
      was: "€749",
      img: "/images/bestsellers/bestseller-raptor-stoel.webp",
      href: SHOP_PATH,
    },
    {
      id: "bartafel-v-serie-180",
      name: "Bartafel V serie 180×80cm",
      price: "€285",
      was: null,
      img: "/images/bestsellers/bestseller-bartafel-v-serie.webp",
      href: SHOP_PATH,
    },
    {
      id: "bureaustoel-706-cs",
      name: "706 CS Bureaustoel, mesh zwart",
      price: "€325",
      was: null,
      img: "/images/bestsellers/bestseller-706-cs.webp",
      href: SHOP_PATH,
    },
  ],
  showroom: {
    name: "Office Image Kantoormeubelen",
    address: "Industrieweg 167",
    zip: "3044 AS Rotterdam",
    img: "/images/showroom/showroom-premium.webp",
    heroImg: "/images/showroom/showroom-hero.webp",
    tel: "010 230 99 44",
    telHref: "tel:0102309944",
    mobile: "+31 6 22778481",
    mobileHref: "tel:+31622778481",
    email: "info@officeimage.nl",
    kvk: "71542027",
  },
  social: {
    facebook: "https://www.facebook.com/officeimage.kantoormeubelen",
    instagram: "https://www.instagram.com/officeimage.kantoormeubelen/",
    linkedin: "https://www.linkedin.com/company/office-image-kantoormeubelen/",
    googleReviews: "https://maps.app.goo.gl/DmaN7imZqGqFfRUV6",
  },
  hours: [
    ["Maandag", "09:00 tot 17:30"],
    ["Dinsdag", "09:00 tot 17:30"],
    ["Woensdag", "09:00 tot 17:30"],
    ["Donderdag", "09:00 tot 17:30"],
    ["Vrijdag", "09:00 tot 17:30"],
    ["Zaterdag", "11:00 tot 16:00"],
    ["Zondag", "Gesloten"],
  ] as const,
  footer: {
    tagline: "LUXE KANTOORINRICHTING, ROTTERDAM & LANDELIJK",
    description:
      "Als jong en dynamisch bedrijf biedt Office Image u een unieke mogelijkheid snel en gemakkelijk te bestellen. Exclusieve directiemeubelen, werkplekken en archiefkasten uit eigen voorraad.",
    catalog: [
      { label: "Directie meubelen", href: SHOP_PATH },
      { label: "Bureaustoelen & stoelen", href: SHOP_PATH },
      { label: "Tafels", href: SHOP_PATH },
      { label: "Kantoorkasten Archiefkasten", href: SHOP_PATH },
      { label: "Ladenkasten & rolblokken", href: SHOP_PATH },
      { label: "Werkplekken elektrisch", href: SHOP_PATH },
      { label: "Werkplekken Foxline", href: SHOP_PATH },
      { label: "Werkplekken Nieuw Line", href: SHOP_PATH },
      { label: "Werkplekken Slinger", href: SHOP_PATH },
      { label: "Werkplekken T-line", href: SHOP_PATH },
    ],
    info: [
      { label: "Klantenservice", href: "https://officeimage.nl/klantenservice/" },
      { label: "Bezorgen", href: "https://officeimage.nl/bezorgen/" },
      { label: "Betaalmethoden", href: "https://officeimage.nl/betaalmethoden/" },
      { label: "Retourneren", href: "https://officeimage.nl/retourneren/" },
    ],
    terms: [
      { label: "Algemene voorwaarden", href: "https://officeimage.nl/algemene-voorwaarden/" },
      { label: "Privacy policy", href: "https://officeimage.nl/privacy-policy/" },
    ],
    mapsHref:
      "https://www.google.com/maps/search/?api=1&query=Industrieweg+167+3044+AS+Rotterdam",
    appointmentNote: "Buiten openingstijden kunt u ook op afspraak de showroom bezoeken",
  },
};

export type Bestseller = (typeof OI.bestsellers)[number];
